### ISSUE TITLE
Stone added from /ta setupbuy but is no longer obtainable in the game.

### ISSUE THREAD

**Issue by AllDayJon** [BeanHeaDza/TradeAssistant#6]
<html>
<body>

9.0.0 | Stone is no longer obtainable through crafting and has been replaced with a Rock Tag which contains all Rock types.
-- | --

<br class="Apple-interchange-newline">
</body>
</html>

![image](https://user-images.githubusercontent.com/3322930/212409326-6b5914f8-6531-4e71-95c4-8efd05045f63.png)

**Comment by BeanHeaDza** [comment]
Fixed in 0.1.7
