### ISSUE TITLE
Price of Crushed Slag cannot be determined

### ISSUE THREAD

**Issue by AllDayJon** [BeanHeaDza/TradeAssistant#8]
It appears that the 0.1.7 release affected the ability to price a number of things. Another example is when doing cooking, it's often easier to set a buy order of Raw Meat, which would be used to calculate all prices instead of adding carcasses, but that no longer seems to work.  Additionally, some items won't price, like crushed slag with mining. 
![image](https://user-images.githubusercontent.com/3322930/215128161-c24408cf-80fe-4076-a64a-0a2899e1672f.png)

**Comment by BeanHeaDza** [comment]
It's actually the 0.1.6 update causing you this problem. I'll have a look at fixing it.

**Comment by BeanHeaDza** [comment]
I would like to see your shop for the cooking example. It should not be problem.

The 0.1.6 update allows you to have something in your buy and sell orders, and then have the mod update the buy price. For slag it obviously doesn't work, because there is no recipe with slag being the main product.

**Comment by AllDayJon** [comment]
I apologize, there's some behavior that isn't intuitive but makes sense mathematically (e.g. making primary products a negative value if a byproduct has a high value.)  The cooking issue was the same problem as the slag, where we had a player who was both buying and selling tomato which doesn't have an associated crafting recipe.

**Comment by BeanHeaDza** [comment]
Yeah, I'm thinking of changing the behaviour, I'm just not sure which way to swing it. i.e. do you treat the sell price as the source of truth and update the buy price, or do you keep the buy price the same and update the sell price? I'm leaning towards keeping the buy price as the source of truth

**Comment by AllDayJon** [comment]
Yeah, there's some interesting stuff with Campfire Cooking and Cooking where the price of Tallow is calculated using the scrap meat recipe (as a primary product), instead of something like Crispy Bacon (where it's a byproduct). but if you want to sell both Campfire Cooking goods and Cooking, you need to buy scrap meat. 

I'm not sure if adding a way to select recipes for price calcs, or ignore certain ones would make sense or just add unneeded complexity. 

For the above, I agree with keeping the buy price as the source of truth

**Comment by BeanHeaDza** [comment]
I'm not sure how the cooking guy had an issue with the tomato price. Before my latest changes in 0.1.8 the mod only updated craftable item prices. I've changed it now though and it's updating the sell price of any item that's listed as both a buy and sell item:
![image](https://user-images.githubusercontent.com/16012107/215301074-26239091-912c-4383-ba17-27297500ba88.png)

The slag issue I also fixed:
![image](https://user-images.githubusercontent.com/16012107/215301122-3824ccd6-125f-4a68-8f82-dad9b2090568.png)
